version: '3.9'

services:
  pihole:
    container_name: ${COMPOSE_PROJECT_NAME}-pihole
    build:
      context: pihole/
      args:
        PIHOLE_VERSION: $PIHOLE_VERSION
    privileged: true
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    ports: 
      - '${IP4_ADDR}:80:80/tcp'
      - '${IP4_ADDR}:53:53/tcp'
      - '${IP4_ADDR}:53:53/udp'
      - '${IP4_ADDR}:67:67/tcp'
      - '${IP4_ADDR}:67:67/udp'
      - '${IP4_ADDR}:443:443/tcp'
    environment:
      - 'ServerIP=${IP4_ADDR}'
      - 'TZ=America/New_York'
      - 'WEBPASSWORD=${PIHOLE_PASSWORD}'
      - 'DNS1=${IP4_ADDR}#5053'
      - 'WEBUIBOXEDLAYOUT=traditional'
      - 'VIRTUAL_HOST=${HOST_NAME}'
      - 'QUERY_LOGGING=true'
      - 'DNSSEC=true'
      - 'DNS_BOGUS_PRIV=true'
      - 'REV_SERVER=true'
      - 'REV_SERVER_TARGET=${ROUTER_IP4}'
      - 'REV_SERVER_CIDR=${ROUTER_CIDR}'
      - 'PIHOLE_DOMAIN=local'
    cap_add:
      - NET_ADMIN
    volumes:
      - './pihole/vol/etc/dnsmasq.d:/etc/dnsmasq.d/'
      - './pihole/vol/etc/pihole/:/etc/pihole/'
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped  
    hostname: ${HOST_NAME}
    networks: 
      - pinet
  
  unbound:
    container_name: ${COMPOSE_PROJECT_NAME}-unbound
    build:
      context: unbound/
      args:
        UNBOUND_VERSION: $UNBOUND_VERSION
    networks: 
      - pinet
    volumes:
      - './unbound/conf/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro'
    ports:
      - '${IP4_ADDR}:5053:5053/udp'
      - '${IP4_ADDR}:5053:5053/tcp'
    restart: unless-stopped
    deploy: 
      resources:
        limits:
          memory: 128M

networks:
  pinet:


# networks:
#   pinet:                         # Name of network
#     driver: macvlan                       # Use the macvlan network driver
#     driver_opts:
#       parent: wlan0                    # If open vSwitch is disabled use eth0 (or eth1 +)
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24        # Specify subnet
#           gateway: 192.168.1.1          # Gateway address
#           ip_range: 192.168.1.203/31    # Available IP addresses
